### ISSUE TITLE
NoMethodError `inst' for Middleman 4.2.0

### ISSUE THREAD

**Issue by sbuenker** [voxmedia/middleman-google_drive#10]
I have a working Middleman instance running, but upon adding and activating this Gem, I keep getting the error below (downgrading to an earlier MM version doesn’t help either). What am I doing wrong? Or is the error is due to the outdatedness of the gem as compared to Middleman v4? 
I’m rather new to this…

```
bundler: failed to load command: middleman (/home/sbuenker/.rbenv/versions/2.3.1/bin/middleman)
NoMethodError: undefined method `inst' for #<Middleman::Application:0x47028529226840>
  /home/sbuenker/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-google_drive-0.2.4/lib/middleman-google_drive/extension.rb:15:in `initialize'
  /home/sbuenker/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/extension_manager.rb:66:in `new'
  /home/sbuenker/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/extension_manager.rb:66:in `activate'
  /home/sbuenker/Code/middleman-docker/middleman/config.rb:30:in `evaluate_configuration!'
  /home/sbuenker/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:329:in `instance_eval'
  /home/sbuenker/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:329:in `evaluate_configuration!'
  /home/sbuenker/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.2.0/lib/middleman-core/application.rb:286:in `initialize'
  /home/sbuenker/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/bin/middleman:49:in `new'
  /home/sbuenker/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.2.0/bin/middleman:49:in `<top (required)>'
  /home/sbuenker/.rbenv/versions/2.3.1/bin/middleman:23:in `load'
  /home/sbuenker/.rbenv/versions/2.3.1/bin/middleman:23:in `<top (required)>'
```

**Comment by ryanmark** [comment]
This extension has not been tested with Middleman 4, so it's likely the source of this problem. We are still stuck on Middleman 3.

**Comment by bendangelo** [comment]
Are there plans to upgrade it to work with 4?
